name: Pyre

on:
  pull_request: {}

jobs:
  pyre:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Poetry
      run: pip install poetry

    - name: Install Dependencies
      run: poetry install --with ci

    - name: Run Pyre Action
      run: poetry run pyre
